FROM node:20

WORKDIR /app

# Copy only package files first (for efficient Docker caching)
COPY ./FontLoom_web/package*.json ./

# Install dependencies
RUN npm install

COPY ./FontLoom_web .

EXPOSE 3000

# CMD ["npm","run","dev"]
CMD ["npm","start"]